FROM python:3.12.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /etl

COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

ENTRYPOINT [ "python", "main.py" ]

CMD [ "python", "main.py" ]